name: Build backend

on:
  push:
    branches: [main, dev]
  pull_request:
    branches:
      - main
    paths:
        - "backend/**"
        - ".github/workflows/backend.yml"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ghcr.io/narah111/ocp-guestbook/
  IMAGE_REGISTRY: ghcr.io/narah111/ocp-guestbook
  IMAGE_NAME: backend
  INFRA_REPO: narah111/infra_openshift


jobs:

  build-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set platform based on branch
        id: platform
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ] && [ "${{ github.base_ref }}" == "main" ]; then
            echo "platforms=linux/amd64" >> $GITHUB_OUTPUT
            echo "Building for amd64 (PR to main)"
          elif [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            echo "platforms=linux/arm64" >> $GITHUB_OUTPUT
            echo "Building for arm64 (dev branch)"
          else
            echo "platforms=linux/amd64" >> $GITHUB_OUTPUT
            echo "Building for amd64 (default)"
          fi

      - name: QEMU Setup
        uses: docker/setup-qemu-action@v3
        with:
            platforms: ${{ steps.platform.outputs.platforms }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate image tag
        id: image-tag
        run: |
            SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
            IMAGE_TAG="1.0.${GITHUB_RUN_NUMBER}-${SHORT_SHA}"
            echo "tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
            echo "Generated tag: ${IMAGE_TAG}"

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
            context: ./backend
            file: ./backend/Containerfile
            platforms: ${{ steps.platform.outputs.platforms }}
            push: ${{ github.event_name != 'pull_request' }}
            
            tags: |
                ghcr.io/narah111/ocp-guestbook/backend:latest
                ghcr.io/narah111/ocp-guestbook/backend:${{ github.sha }}

      - name: Update Kubernetes manifests
        if: github.event_name == 'pull_request'
        run: |
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"

            git clone https://${{ secrets.INFRA_OPENSHIFT }}@github.com/${{ env.INFRA_REPO }}.git infra_openshift
            cd infra_openshift

            sed -i "s|image: .*backend:.*|image: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.image-tag.outputs.tag }}|" k8s/backend.yml
            sed -i "s|value: \".*\"|value: \"${{ steps.image-tag.outputs.tag }}\"|" k8s/backend.yml

            git add k8s/backend.yml
            git commit -m "Update image to ${{ steps.image-tag.outputs.tag }}"
            git push origin main